### ISSUE TITLE
Crash (??) on solution load

### ISSUE THREAD

**Issue by ErikEJ** [BlackbirdSQL/Firebird-DDEX-SqlEditor#28]
See this in the output window with 11.1.0.2:

IDE::EXCEPTION: 08.55.28.386279:   LoadSolutionConfiguredConnections :: BlackbirdSql.Core\Model\AbstruseRunningConnectionTable.cs :: 1145
	Specified cast is not valid. 
TRACE:    at BlackbirdSql.Core.UnsafeCmd.IsValidExecutableProjectType(Project project, Boolean validateCps) in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql.Core\Root\UnsafeCmd.cs:line 282
   at BlackbirdSql.Core.Model.AbstruseRunningConnectionTable.RecursiveScanProject(Project project) in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql.Core\Model\AbstruseRunningConnectionTable.cs:line 1677
   at BlackbirdSql.Core.Model.AbstruseRunningConnectionTable.LoadSolutionConfiguredConnections(CancellationToken cancellationToken, Boolean isSync, Object probject) in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql.Core\Model\AbstruseRunningConnectionTable.cs:line 1141

**Comment by BlackbirdSQL** [comment]
A fix has been implemented for the next build which basically checks for int, long and string before defaulting to unknown.

Do you know what type of projects are in the solution it is crashing in then I can identify the type coming out of `OutputType`, which "should" be an int.

**Comment by ErikEJ** [comment]
The project is the Open source EF Core Power Tools,  so you can just clone that.

**Comment by BlackbirdSQL** [comment]
Okay I do have that, I will try and open it. I think one of the projects has the property but it's value is returning null, so I've implemented a check for that IAC.

**Comment by BlackbirdSQL** [comment]
I have tested with the solution at [https://github.com/ErikEJ/EFCorePowerTools](https://github.com/ErikEJ/EFCorePowerTools).

I'm not getting anything but I've nonetheless implemented multiple checks and gracefully handled any exceptions.

I've also put in a temporary trace so if you `Enable trace` and `Enable tracer` it will appear in the output log window from which the value and type can be identified, which would help me.
The only project that gets tested on my side is `WizardItemTemplate` and that has an Int32 value. 

Just doing final testing on the next build which implements optional TTS in the SqlEditor and then I'll upload with that fix.

**Comment by BlackbirdSQL** [comment]
This issue has been resolved in Release 11.1.1.0.
