### ISSUE TITLE
I get problem when trying to connect to firebird db 3.0

### ISSUE THREAD

**Issue by mkmita** [BlackbirdSQL/Firebird-DDEX-SqlEditor#70]
Hello,

I use this extension on visual studio 2022 and when i try to connect to firebird db 3.0 using server explorer i get this error.

![Screenshot 2024-08-10 211737](https://github.com/user-attachments/assets/776957d0-0e0a-4c1d-918b-52748989b744)

Maybe you can help?

Best Regards.

**Comment by BlackbirdSQL** [comment]
This issue has been resolved in the next release, Version 14.0.0.4. All cases where version mismatches could occur should be addressed in this release.
It will be available for download either later today or tomorrow.

**Comment by BlackbirdSQL** [comment]
Okay I see you have version 4.1 of the Firebird client. The extension only covered back to version 6. I will include all previous versions in the assembly version tables and post an update.

**Comment by BlackbirdSQL** [comment]
Release 14.0.0.1 is the patch to support legacy projects using Firebird client versions prior to version 6.0.0.
You can update the extension to release 14.1.0.1 or download using the link below.

[Download BlackbirdSql DDEX with SqlEditor Extension (Release v14.1.0.1)](https://github.com/BlackbirdSQL/Firebird-DDEX-SqlEditor/releases/download/v14.1.0.1/BlackbirdSql.VisualStudio.Ddex.vsix) ([Change Log](https://github.com/BlackbirdSQL/Firebird-DDEX-SqlEditor/blob/master/Docs/CHANGELOG.md))

Please give me feedback on whether or not this works for you.
