### ISSUE TITLE
Extension can't be loaded in VS 2022 17.8 LTSC

### ISSUE THREAD

**Issue by MagicAndre1981** [BlackbirdSQL/Firebird-DDEX-SqlEditor#73]
In the extension manifest you [claim it works since 17.0](https://github.com/BlackbirdSQL/Firebird-DDEX-SqlEditor/blob/ddad3ddb09eb43df4a139ffd11d40a5143b66e26/BlackbirdSql.VisualStudio.Ddex/source.extension.vsixmanifest#L15), but in reality the extension only works since 17.10:

> CreateInstance failed for package [BlackbirdSqlDdexExtension]Source: 'mscorlib' Description: Exception has been thrown by the target of an invocation.
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Die Datei oder Assembly "**Microsoft.VisualStudio.Threading, Version=17.10**.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
>    at BlackbirdSql.Sys.AbstrusePackageController..ctor(IBsAsyncPackage ddex)
>    at BlackbirdSql.Controller.ControllerPackage.CreateController() in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql.Controller\ControllerPackage.cs:line 286
>    at BlackbirdSql.Core.AbstractCorePackage..ctor() in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql.Core\AbstractCorePackage.cs:line 66
>    at BlackbirdSql.EditorExtension.EditorExtensionPackage..ctor() in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql.EditorExtension\EditorExtensionPackage.cs:line 133
>    at BlackbirdSql.Controller.ControllerPackage..ctor() in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql.Controller\ControllerPackage.cs:line 43

So, update the manifest entry to 17.10 to avoid installs on unsupported VS2022 versions.

**Comment by BlackbirdSQL** [comment]
Hmmm.., yes thanks for the heads up. Release 14.5 will be uploaded today. It resolves many minor and major bugs. Some of these bugs could cause the IDE to hang under certain conditions. I am fairly confident version 14.5 will be the most stable that has been released to date.
The update up to 17.10 is necessary because `Microsoft.VisualStudio.Threading` has been buggy since 17.0, otherwise I would just roll back to 17.0 for you. Version 17.10 is the first release since before 17.0 that seems to have ironed out all the issues.

**Comment by MagicAndre1981** [comment]
I'm ok with this, I also made the update to 17.10 LTSC. So change the version range in the extension manifest to 17.10

`<InstallationTarget Id="Microsoft.VisualStudio.Enterprise" Version="[17.10, 18.0)">`

**Comment by BlackbirdSQL** [comment]
Done!

**Comment by BlackbirdSQL** [comment]
Release 14.5 has been uploaded. You can view the [Changelog here](https://github.com/BlackbirdSQL/Firebird-DDEX-SqlEditor/discussions/74), Andre.
