### ISSUE TITLE
Can't select FDB file in Server Explorer when trying to add a connection

### ISSUE THREAD

**Issue by MagicAndre1981** [BlackbirdSQL/Firebird-DDEX-SqlEditor#81]
I can't select a FDB file in Server Explorer when trying to add a connection. After clicking `Open` the string is empty

![image](https://github.com/user-attachments/assets/68f5c3e2-3477-4844-aba5-df7924f15d8e)

![image](https://github.com/user-attachments/assets/be2000f1-d7a5-477e-bc43-027b94a6ad02)

In the dialog I have to do a right click and select copy as path

![image](https://github.com/user-attachments/assets/e0d15a3b-a434-4173-bf76-e3de9b27de56)

and manually paste it into the `Database` textbox:

![image](https://github.com/user-attachments/assets/d137d3cf-a37f-411a-852e-6ffafdb8348d)

**Comment by BlackbirdSQL** [comment]
The only thing I see is the space in `Program Files` could be causing this. I'm going to test a database with long file names in the path.
Until I locate the issue you could try using the dos 8.2 name as a workaround.
At the command prompt use the `dir /x` command. Should be `progra~1`.

**Comment by BlackbirdSQL** [comment]
The issue with the empty string has been resolved in the next release. The value from the File Dialog was being assigned to the drop down combo box instead of the text box overlay in the database control region.
This does not address your second issue #82.

**Comment by MagicAndre1981** [comment]
works fine with 14.5.1.3 👍
