### ISSUE TITLE
Open a table in designer causes messagebox "Illegal characters in path"

### ISSUE THREAD

**Issue by MagicAndre1981** [BlackbirdSQL/Firebird-DDEX-SqlEditor#82]
After I figured out how to add a database to Server explorer (#81) I have a new issue. When I open a table in designer

![image](https://github.com/user-attachments/assets/02d51723-9080-40fb-983f-80ebb691140e)

I get this message:

![image](https://github.com/user-attachments/assets/1ef12418-6ee7-44e9-a673-b92eabfcfd0d)

I don't have a solution open and only tried to check if the database can be accessed. 

I've enabled the diag logger option but get no extra details.

**Comment by BlackbirdSQL** [comment]
The issue with the empty string is resolved in the next release. See #81.
I am unable to replicate your second issue after you have opened the table in the designer, with and without a solution open.
I will upload a patch for #81 in the next few hours and suggest you delete the connection, then close and reopen Visual Studio, and then add the the database using the "working" file dialog to select the database file, and then retest it.
It is important to close and reopen Visual Studio before recreating the connection to be sure the deleted connection is not being reused. This would not normally be an issue but we want to be sure we're testing on a completely new connection.

I will let you know as soon as the update is uploaded.

**Comment by MagicAndre1981** [comment]
> The issue with the empty string is resolved in the next release. See #81. I am unable to replicate your second issue after you have opened the table in the designer, with and without a solution open.

ok, looks like this comes from an ArgumentException in `System.IO.Path.GetExtension(System.String)` in **BlackbirdSql.Controller.dll!BlackbirdSql.Controller.ControllerEventsManager::[OnBeforeDocumentWindowShow](https://github.com/BlackbirdSQL/Firebird-DDEX-SqlEditor/blob/e91357c73edce0c66d9aa5469dfc44841cc2280e/BlackbirdSql.Controller/ControllerEventsManager.cs#L1073)** which is this call:

`string ext = Path.GetExtension(docInfo.Moniker);`

![image](https://github.com/user-attachments/assets/6b89e353-16b5-41e9-b9cc-9c22b5a8bbb3)

![image](https://github.com/user-attachments/assets/cee9466d-bf07-40a7-a7d6-9720aacdaed6)

The [ETW code looks wired you use](https://github.com/BlackbirdSQL/Firebird-DDEX-SqlEditor/blob/master/BlackbirdSql.Sys/Ctl/Diagnostics/SqlEtwProvider.cs) and I was not able to capture the data with wpr.exe and my wprp profile file, so I only found the .net exception and it was still helpful even without your ETW events.

**Comment by BlackbirdSQL** [comment]
Yes. I want to clear out the MS SqlServer etw because it's mostly redundant for Firebird, so it's unhooked atm.
It needs a rewrite to something much simpler.
`Path.GetExtension(docInfo.Moniker)` is a handled expected exception so the issue shouldn't be there; but the `Path` class is used extensively elsewhere and possibly throwing an unhandled exception, so that will be a good place to start. 
From your screenshots it looks like the error is appearing after the designer is open, because that is a Microsoft package which may explain why you're not able to pick up anything? It could be swallowing up exceptions thrown by BlackbirdSql.
If possible, don't delete the connection that's giving problems so that we can use it as a reference. We can create a new distinct connection using the `Application Name` connection parameter to test on.

**Comment by BlackbirdSQL** [comment]
Okay I've uploaded to VSIX Gallery. Not exactly sure how it works but it is appearing in the feed.
The Path class now has wrappers for all methods that work on a supplied path so you shouldn't see any exceptions. The paths are cleaned in the wrapper methods so if there are any spurious common non-printable characters they'll be removed.
Could you give it a shot a let me know?

**Comment by MagicAndre1981** [comment]
The message was still there, but the callstack now differed. I was now able to see that the extension from syncfusion (MAUI, Xamarin) caused it.

Sorry for the trouble.

**Comment by BlackbirdSQL** [comment]
No, it's no trouble at all. Your input is valued.
If there's anything you'd like to see improved or added to the extension, let me know and I'll see if it can be done.
