### ISSUE TITLE
Provide Preview versions of extension updates on VSIX Gallery

### ISSUE THREAD

**Issue by MagicAndre1981** [BlackbirdSQL/Firebird-DDEX-SqlEditor#83]
If you want to (for example let me) test some bugfixes, provide a version on [VSIX Gallery](https://www.vsixgallery.com/) first, so that only users who [added this source in VS 2022 ](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VSIXGallery-nightlybuilds)will get the update offered. 

![image](https://github.com/user-attachments/assets/b8268470-a773-49d7-9644-e1d09749956f)

If the fixes work for the people who submitted issues, release a new official version to the VS market place. 

**Add your extension**
https://www.vsixgallery.com/devguide

**Comment by BlackbirdSQL** [comment]
Yes great. Okay thanks I'll do that.

**Comment by MagicAndre1981** [comment]
works fine, got 2 updates 👍
